PRECOMPUTED_PATH = ''
PDB_PATH = ''
FLIPS = (0.2, 0.2, 0.2)
MAX_RADIUS = 40
NOISE_TREATMENT = False
INPUT_CHANNELS = 3
P = 0
SCALING_WEIGHTS = True
SHUFFLE = False
V_SIZE = 32
WEIGHTS = []                # 'hydropathy', 'charge', 'isoelectric'
